### PR TITLE
Get GlotPress locale slug by WordPress locale code

### PR DESCRIPTION
**Pull request by pedro-mendonca**
Solves https://github.com/mayukojpn/gp-live-export/issues/6

### CODE REVIEW

**Comment by pedro-mendonca** [comment]
@mayukojpn I've replicated the same include GlotPress library for locales as you did on https://github.com/mayukojpn/force-update-translations/commit/5ae0c88181911846d2aac942e8aceda179657fb4.

Not sure if this is needed, because both are GlotPress dependent plugins and GlotPress has that locale list.
Still, I've added it as fallback as you did in FUT.

**Review by mayukojpn — CHANGES_REQUESTED** [review]
Wow it was quick, thank you so much!
Though Force Update Translations doesn't need self hosted GP, this plugin should work with it. GP installation is checked [here](https://github.com/mayukojpn/gp-live-export/blob/33c193f6ec0b954f28e5de8d4cb0cdabff291ce2/gp-live-export.php#L66).

**Review by mayukojpn — APPROVED** [review]

**Comment by pedro-mendonca** [comment]
I think you just did it :)

**Comment by mayukojpn** [comment]
@pedro-mendonca I'm testing all GitHub features 😅

**Pull request merged**
